stages:
  - push-develop-to-kabam

push-develop-to-kabam:
  stage: push-develop-to-kabam
  script:
    - git push https://$GITHUB_AUTH_TOKEN@github.com/$GITHUB_USERNAME/test-pushes-automatization.git master
  only:
    - master
    - web